### ISSUE TITLE
[blog] tag descriptions

### ISSUE THREAD

**Issue by preaction** [preaction/Statocles#257]
We should be able to have markdown lead-ins for tags.

**Comment by preaction** [comment]
On my food blog, it'd be nice if I could take the "easy" tag and describe what I mean by it (few ingredients). Or take the "pasta" tag and add some basic notes on pasta like how to cook it.

Since these might be long, it might be prudent to put them in another file, like #215.

**Comment by preaction** [comment]
So, given the syntax proposed by preaction/Beam-Wire#3 (through Statocles #215), it would look kind of like this:

```yaml
# site.yml
blog:
    class: Statocles::App::Blog
    args:
        url_root: /blog
        store: blog
        data:
            tags: { $config: data/tags.yml }
```
```yaml
# data/tags.yml
pasta: |-
    Pasta is a stiff dough made of flour and egg, and then cooked in water.

    ![](/images/pasta-cooking.jpg)

    _al dente_ pasta is chewy.

easy: |-
    These recipes have few ingredients are are simple to put together for a busy night's dinner.
```

I love yaml's heredoc stuff. Just. Absolutely. Perfect for this.
