### ISSUE TITLE
[linkcheck] Add url roots to ignore

### ISSUE THREAD

**Issue by preaction** [preaction/Statocles#272]
My blog has a few parts that are generated by github pages, like `/ETL-Yertl` and `/Statocles`, so links to those parts will never be right.

I could force an `http://preaction.github.io/`, but it'd be nice if I could just say which URLs don't need to be checked.

I should be able to set an array of ignores. Ignores should be pattern matches, like so:

```yaml
# site.yml
site:
    on:
        - build:
            $class: Statocles::Plugin::LinkCheck
            $args:
                ignore:
                    - '/ETL-Yertl'
                    - '/Statocles'
            $method: check_pages
```

This apparently makes it more difficult to use the anonymous syntax. We should change the name to "$handler" instead!
