### ISSUE TITLE
DBI application

### ISSUE THREAD

**Issue by preaction** [preaction/Statocles#301]
There could be a way to make static displays of any database. A way to map a query to a template, like:

```yaml
users:
    class: Statocles::App::Database
    args:
        dbh:
            $class: DBI
            $method: connect
            $args:
                - 'dbi:SQLite:users.db'
        username:
        pages:
            /index.html
                query: SELECT * FROM users
                template: users/index.html
            /user/:user.html
                query: SELECT * FROM users JOIN profile ON users.id = profile.user_id WHERE users.id = :user
                template: users/profile.html
```

The templates should have a way to execute arbitrary database queries too, using a helper.
