### ISSUE TITLE
Option to use Text::MultiMarkdown for rendering.

### ISSUE THREAD

**Issue by AdUser** [preaction/Statocles#389]
[This](https://metacpan.org/pod/Text::MultiMarkdown) module has the same author as Text::Markdown and extends it by redefining some methods.

It brings some additional features like footnotes or limited math formulas support.

**Comment by preaction** [comment]
You should be able to specify a Text::Markdown object as the `markdown` attribute of your Site object:

```
site:
    class: Statocles::Site
    args:
        apps: ...
        title: ...
        # ... etc...
        markdown:
            $class: Text::MultiMarkdown
```

Any object that specifies a `markdown` method that takes in content and returns HTML will work. I'll add some better documentation to the Config guide.
