### ISSUE TITLE
Theme templates gets copied into deploy destdir

### ISSUE THREAD

**Issue by AdUser** [preaction/Statocles#399]
Tested on 0.055. Part of config with theme- and deploy-related settings:

```yaml
site:
  args:
    theme:
      $ref: theme
deploy:
  args:
    path: html
  class: Statocles::Deploy::File
theme:
  args:
    store: theme
  class: Statocles::Theme
```
Try to run deploy:

```
me@localhost:~/site$ statocles deploy
me@localhost:~/site$ find html/ -name '*.ep'
html/theme/blog/index.rss.ep
html/theme/blog/index.html.ep
html/theme/blog/index.atom.ep
html/theme/blog/post.html.ep
html/theme/site/sitemap.xml.ep
html/theme/site/robots.txt.ep
html/theme/site/layout.html.ep
```

It's not critical, but potentially may expose private data.
