### ISSUE TITLE
syntax highlighting with https://highlightjs.org/

### ISSUE THREAD

**Issue by natxo** [preaction/Statocles#405]
is it possible to use the js libraries in the frontmatter?

I have tried this:

```
---
title: whatever
links:
    script:                                                                     
        - href: http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/highlight.min.js
    stylesheet:
        - href: http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/styles/default.min.css     
---
```

but I still need to load the function initHighlightingOnLoad using `<script>hljs.initHighlightingOnLoad();</script>` (see https://highlightjs.org/usage/)

I do not see in the link objects how I could do this, but I am probably missing something basic. Is this doable?

Thanks in advance.
