### ISSUE TITLE
Update Statocles configs for new Beam::Wire bare services

### ISSUE THREAD

**Issue by preaction** [preaction/Statocles#478]
With the new Beam::Wire v1.018, we have bare services. These services do not need a class or args in the root of their configuration hash. So, whereas now we have:

```
site:
    class: Statocles::Site
    args:
        apps:
            # ...
```

Using bare services we can make it look like:

```
site:
    apps:
        # ...
```

We will need to make a default class of `Statocles::Site`, of course. If users want to override that, they can do:

```
site:
    $class: My::Site
```

To add roles:

```
site:
    $with: My::Role
```

And etc...

This will clean up the configuration quite a bit, and make it look more like configuration and less like code.
